//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMad_backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioMad_backend.Resources.Areas.Share.Views.Home.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О биомаркере.
        /// </summary>
        internal static string aboutBiomarker {
            get {
                return ResourceManager.GetString("aboutBiomarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биомаркеры.
        /// </summary>
        internal static string biomarkers {
            get {
                return ResourceManager.GetString("biomarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string biomarkerType {
            get {
                return ResourceManager.GetString("biomarkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее значение.
        /// </summary>
        internal static string currentValue {
            get {
                return ResourceManager.GetString("currentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представлены последние {0} показателей.
        /// </summary>
        internal static string historyDesc {
            get {
                return ResourceManager.GetString("historyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История биомаркеров.
        /// </summary>
        internal static string pageTitle {
            get {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациент.
        /// </summary>
        internal static string patient {
            get {
                return ResourceManager.GetString("patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Референсы подобраны по параметрам пациента.
        /// </summary>
        internal static string referenceDescDefault {
            get {
                return ResourceManager.GetString("referenceDescDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Референсы выставлены самим пациентом.
        /// </summary>
        internal static string referenceDescOwn {
            get {
                return ResourceManager.GetString("referenceDescOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норма.
        /// </summary>
        internal static string referenceNormal {
            get {
                return ResourceManager.GetString("referenceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Референсы.
        /// </summary>
        internal static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите биомаркер в меню слева чтобы увидеть подробности.
        /// </summary>
        internal static string selectBiomarker {
            get {
                return ResourceManager.GetString("selectBiomarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С вами поделились анализами.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
