CREATE TABLE "Culture" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    CONSTRAINT "PK_Culture" PRIMARY KEY ("Id")
);

CREATE TABLE "GenderTranslation" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "BaseEntityId" integer NOT NULL,
    CONSTRAINT "PK_GenderTranslation" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GenderTranslation_Genders_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "Genders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GenderTranslation_Culture_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Culture" ("Id") ON DELETE CASCADE
);

INSERT INTO "Culture" ("Id", "Key")
VALUES (1, 'en');
INSERT INTO "Culture" ("Id", "Key")
VALUES (2, 'ru');

CREATE INDEX "IX_GenderTranslation_BaseEntityId" ON "GenderTranslation" ("BaseEntityId");

CREATE INDEX "IX_GenderTranslation_CultureId" ON "GenderTranslation" ("CultureId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201110160347_Localization', '3.1.9');

ALTER TABLE "Users" ADD "CultureId" integer NULL;

CREATE INDEX "IX_Users_CultureId" ON "Users" ("CultureId");

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Culture_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Culture" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201111092535_CultureTactic', '3.1.9');

ALTER TABLE "GenderTranslation" DROP CONSTRAINT "FK_GenderTranslation_Culture_CultureId";

ALTER TABLE "Users" DROP CONSTRAINT "FK_Users_Culture_CultureId";

ALTER TABLE "Culture" DROP CONSTRAINT "PK_Culture";

ALTER TABLE "Culture" RENAME TO "Cultures";

ALTER TABLE "Cultures" ADD "Name" text NULL;

ALTER TABLE "Cultures" ADD CONSTRAINT "PK_Cultures" PRIMARY KEY ("Id");

UPDATE "Cultures" SET "Name" = 'English'
WHERE "Id" = 1;

UPDATE "Cultures" SET "Name" = 'Русский'
WHERE "Id" = 2;

ALTER TABLE "GenderTranslation" ADD CONSTRAINT "FK_GenderTranslation_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE;

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201111205501_CultureAdded', '3.1.9');

