CREATE TABLE "BiomarkerReferenceConfigDependencyRanges" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Lower" double precision NOT NULL,
    "Upper" double precision NOT NULL,
    CONSTRAINT "PK_BiomarkerReferenceConfigDependencyRanges" PRIMARY KEY ("Id")
);

CREATE TABLE "BiomarkerReferences" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Value" double precision NOT NULL,
    "BiomarkerId" integer NOT NULL,
    CONSTRAINT "PK_BiomarkerReferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BiomarkerReferences_Biomarkers_BiomarkerId" FOREIGN KEY ("BiomarkerId") REFERENCES "Biomarkers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BiomarkerReferenceConfigs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ReferenceId" integer NOT NULL,
    "GenderId" integer NOT NULL,
    CONSTRAINT "PK_BiomarkerReferenceConfigs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BiomarkerReferenceConfigs_Genders_GenderId" FOREIGN KEY ("GenderId") REFERENCES "Genders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BiomarkerReferenceConfigs_BiomarkerReferences_ReferenceId" FOREIGN KEY ("ReferenceId") REFERENCES "BiomarkerReferences" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BiomarkerReferenceUsers" (
    "BiomarkerReferenceId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_BiomarkerReferenceUsers" PRIMARY KEY ("UserId", "BiomarkerReferenceId"),
    CONSTRAINT "FK_BiomarkerReferenceUsers_BiomarkerReferences_BiomarkerRefere~" FOREIGN KEY ("BiomarkerReferenceId") REFERENCES "BiomarkerReferences" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BiomarkerReferenceUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BiomarkerReferenceConfigDependencies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Type" integer NOT NULL,
    "RangeId" integer NOT NULL,
    "ConfigId" integer NOT NULL,
    CONSTRAINT "PK_BiomarkerReferenceConfigDependencies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BiomarkerReferenceConfigDependencies_BiomarkerReferenceConf~" FOREIGN KEY ("ConfigId") REFERENCES "BiomarkerReferenceConfigs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BiomarkerReferenceConfigDependencies_BiomarkerReferenceCon~1" FOREIGN KEY ("RangeId") REFERENCES "BiomarkerReferenceConfigDependencyRanges" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BiomarkerReferenceConfigDependencies_ConfigId" ON "BiomarkerReferenceConfigDependencies" ("ConfigId");

CREATE INDEX "IX_BiomarkerReferenceConfigDependencies_RangeId" ON "BiomarkerReferenceConfigDependencies" ("RangeId");

CREATE INDEX "IX_BiomarkerReferenceConfigs_GenderId" ON "BiomarkerReferenceConfigs" ("GenderId");

CREATE UNIQUE INDEX "IX_BiomarkerReferenceConfigs_ReferenceId" ON "BiomarkerReferenceConfigs" ("ReferenceId");

CREATE INDEX "IX_BiomarkerReferences_BiomarkerId" ON "BiomarkerReferences" ("BiomarkerId");

CREATE INDEX "IX_BiomarkerReferenceUsers_BiomarkerReferenceId" ON "BiomarkerReferenceUsers" ("BiomarkerReferenceId");

CREATE UNIQUE INDEX "IX_BiomarkerReferenceUsers_UserId_BiomarkerReferenceId" ON "BiomarkerReferenceUsers" ("UserId", "BiomarkerReferenceId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201113122502_BiomarkerRef', '3.1.9');

ALTER TABLE "BiomarkerReferences" ADD "UnitId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_BiomarkerReferences_UnitId" ON "BiomarkerReferences" ("UnitId");

ALTER TABLE "BiomarkerReferences" ADD CONSTRAINT "FK_BiomarkerReferences_Units_UnitId" FOREIGN KEY ("UnitId") REFERENCES "Units" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201113123012_BiomarkerUnit', '3.1.9');

